appointments: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.1/appointments-1.3.0-SNAPSHOT-2.1.0.omod
bahmni_core: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.1/bahmnicore-0.93-SNAPSHOT-2.6.0.omod
bahmni_ie_apps: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.1/bahmni.ie.apps-1.1.0-SNAPSHOT-2.5.0.omod
bahmniapps: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.1/bahmniapps-2.6.1.zip
implementer_interface: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.1/bahmni-implementer-interface-91-2.6.1.noarch.rpm
appointment_frontend: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.1/appointment-frontend-2.5.0.zip
emr_api_omod: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.1/emrapi-omod-1.24.7-2.1.0-SNAPSHOT.omod
event_omod: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.1/event-2.8.0-2.1.0.omod
uiframework: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.1/uiframework-3.19-2.1.0.omod
visitclosemodule: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.1/visit-close-module-0.93-2.3.1.omod